name: CringePvP
main: de.coaster.cringepvp.CringePvP
version: "1.20"
description: "Das eine System, alle anderen zu unterwerfen."
author: "CoasterFreakDE"
api-version: "1.20"
depend:
  - TAB
  - DecentHolograms
  - PlaceholderAPI
  - Votifier